- name: install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present
  when: ansible_os_family == "Debian"

- name: sync config for LOCAL
  import_tasks: local.yml
  when: ansible_connection == "local"

- name: sync config for REMOTE
  import_tasks: remote.yml
  when: not ansible_connection == "local"

- name: ensure ~/.config exists
  ansible.builtin.file:
    path: ~/.config
    state: directory

- name: get starship
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/starship
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: get eza
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/eza
    extra_opts:
      - --strip-components=1
      - ./eza
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: bat version
  ansible.builtin.uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
    # headers:
    #   Authorization: '{{ token }}'
  register: repo

- name: get bat
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/sharkdp/bat/releases/latest/download/bat-{{ repo.json.tag_name }}-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/bat
    extra_opts:
      - --strip-components=1
      - bat-{{ repo.json.tag_name }}-x86_64-unknown-linux-gnu/bat
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: zoxide version
  ansible.builtin.uri:
    url: https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest
    # headers:
    #   Authorization: '{{ token }}'
  register: repo

- name: get zoxide
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/ajeetdsouza/zoxide/releases/latest/download/zoxide-{{ repo.json.tag_name | replace("v", "") }}-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/zoxide
    include: zoxide
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: fzf version
  ansible.builtin.uri:
    url: https://api.github.com/repos/junegunn/fzf/releases/latest
    # headers:
    #   Authorization: '{{ token }}'
  register: repo

- name: get fzf
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/junegunn/fzf/releases/latest/download/fzf-{{ repo.json.tag_name }}-linux_amd64.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/fzf
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: lazygit version
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    # headers:
    #   Authorization: '{{ token }}'
  register: repo

- name: get lazygit
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ repo.json.tag_name | replace("v","") }}_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/lazygit
    include: lazygit
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: delta version
  ansible.builtin.uri:
    url: https://api.github.com/repos/dandavison/delta/releases/latest
    # headers:
    #   Authorization: '{{ token }}'
  register: repo

- name: get delta
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/dandavison/delta/releases/latest/download/delta-{{ repo.json.tag_name }}-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/delta
    extra_opts:
      - --strip-components=1
      - delta-{{ repo.json.tag_name }}-x86_64-unknown-linux-gnu/delta
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: ripgrep version
  ansible.builtin.uri:
    url: https://api.github.com/repos/BurntSushi/ripgrep/releases/latest
  register: repo

- name: get ripgrep
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/BurntSushi/ripgrep/releases/latest/download/ripgrep-{{ repo.json.tag_name }}-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/rg
    extra_opts:
      - --strip-components=1
      - ripgrep-{{ repo.json.tag_name }}-x86_64-unknown-linux-musl/rg
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: fd version
  ansible.builtin.uri:
    url: https://api.github.com/repos/sharkdp/fd/releases/latest
  register: repo

- name: get fd
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/sharkdp/fd/releases/latest/download/fd-{{ repo.json.tag_name }}-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/fd
    extra_opts:
      - --strip-components=1
      - fd-{{ repo.json.tag_name }}-x86_64-unknown-linux-musl/fd
    remote_src: true
    mode: '0755'
    owner: root
    group: root

- name: get btop
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/aristocratos/btop/releases/latest/download/btop-x86_64-linux-musl.tbz
    dest: /usr/local/bin
    creates: /usr/local/bin/btop
    extra_opts:
      - --strip-components=3
      - ./btop/bin/btop
    remote_src: true
    mode: '0755'
    owner: root
    group: root
