#!/bin/bash

set -e

case "$1" in
    all | neovim) ;;
    *)
        if [[ -z "$1" ]]; then
            echo 'ERROR: no playbook chosen'
        else
            echo "ERROR: playbook '$1' not found"
        fi
        echo 'Usage: run <PLAYBOOK>'
        echo 'Playbooks:'
        echo '  all       Configure everyting'
        echo '  neovim    Configure neovim'
        exit 1
        ;;
esac

SECRETS="secrets.yml"
if [[ ! -e "$SECRETS" ]]; then
    echo 'ERROR: secrets not configured'
    exit 1
fi

REMOTE="hosts/remote.yml"
if [[ ! -e "$REMOTE" ]]; then
    cp "templates/remote_default.yml" "$REMOTE"
fi

git submodule update --init --recursive

VENV=${VENV:-.venv}
if [[ ! -d "$VENV" ]]; then
    python3 -m venv $VENV
    source "$VENV/bin/activate" >/dev/null 2>/dev/null
    pip install ansible
fi

if [[ -z "$VIRTUAL_ENV" ]]; then
    source "$VENV/bin/activate" >/dev/null 2>/dev/null
    if [[ $? -ne 0 ]]; then
        echo "Install a virtual env into '$VENV' folder"
        exit 1
    fi
fi

ansible-playbook "playbooks/$1.yml" -i "hosts/local.yml" -i "$REMOTE" -e "@$SECRETS"

deactivate
