#!/bin/bash

case "$1" in
    all | neovim) ;;
    *)
        if [[ -z "$1" ]]; then
            echo 'ERROR: no playbook chosen'
        else
            echo "ERROR: playbook '$1' not found"
        fi
        echo 'Usage: run <PLAYBOOK>'
        echo 'Playbooks:'
        echo '  all  Configure everyting'
        exit 1
        ;;
esac

ansible-playbook "$1-playbook.yml" -i "local.yml" -i "remote.yml" -e "@secrets.yml"
