- name: install tmux
  import_tasks: debian.yml
  when: ansible_facts["os_family"] == "Debian"

- name: ensure ~/.config exists
  ansible.builtin.file:
    path: ~/.config
    state: directory

- name: sync tmux config (remote)
  ansible.posix.synchronize:
    src: tmux
    dest: ~/.config
    delete: true
    rsync_opts:
      - "--exclude=.git"
  when: inventory_hostname in groups["remote"]

- name: link tmux config (local)
  ansible.builtin.file:
    src: '{{ playbook_dir }}/roles/tmux/files/tmux'
    path: ~/.config/tmux
    state: link
  when: inventory_hostname in groups["local"]
