- name: install tmux
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: install tmux
  become: true
  community.general.zypper:
    name: tmux
    state: present
    disable_recommends: false
  when: ansible_os_family == "Suse"

- name: ensure ~/.config exists
  ansible.builtin.file:
    path: ~/.config
    state: directory

- name: sync tmux config (remote)
  ansible.posix.synchronize:
    src: tmux
    dest: ~/.config
    delete: true
    rsync_opts:
      - "--exclude=.git"
  when: inventory_hostname in groups["remote"]

- name: link tmux config (local)
  ansible.builtin.file:
    src: '{{ playbook_dir }}/roles/tmux/files/tmux'
    path: ~/.config/tmux
    state: link
  when: inventory_hostname in groups["local"]
