- name: ensure ~/.config/systemd/user exists
  ansible.builtin.file:
    path: ~/.config/systemd/user
    recurse: true
    state: directory

- name: copy x410 VSOCK service
  ansible.builtin.copy:
    src: systemd/user/x410.service
    dest: ~/.config/systemd/user/
    force: true
    backup: true
  when: ansible_facts.virtualization_type == "wsl"

- name: start x410 VSOCK service
  ansible.builtin.systemd:
    enabled: true
    name: x410
    state: started
    scope: user
  when: ansible_facts.virtualization_type == "wsl"

- name: set ttl
  become: true
  ansible.builtin.shell: echo 'net.ipv4.ip_default_ttl=65' | tee /etc/sysctl.d/ip_default_ttl.conf
  when: not ansible_facts.virtualization_type == "wsl"
