- name: ensure ~/.config/systemd/user exists
  ansible.builtin.file:
    path: ~/.config/systemd/user
    recurse: true
    state: directory
  when: ansible_facts.virtualization_type == "wsl"

- name: copy x410 VSOCK service
  ansible.builtin.copy:
    src: systemd/user/x410.service
    dest: ~/.config/systemd/user/
    force: true
    backup: true
  when: ansible_facts.virtualization_type == "wsl"

- name: start x410 VSOCK service
  ansible.builtin.systemd:
    enabled: true
    name: x410
    state: started
    scope: user
  when: ansible_facts.virtualization_type == "wsl"

- name: set ttl
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_default_ttl
    value: '65'
    sysctl_file: /etc/sysctl.d/ip_default_ttl.conf
    state: present
  when: not ansible_facts.virtualization_type == "wsl"

- name: set sudo PATH
  become: true
  ansible.builtin.copy:
    src: sudo/path
    dest: /etc/sudoers.d/path
    owner: root
    group: root
    mode: '0640'
    validate: 'visudo -cf %s'

- name: preserve some variables
  become: true
  ansible.builtin.copy:
    src: sudo/env
    dest: /etc/sudoers.d/env
    owner: root
    group: root
    mode: '0640'
    validate: 'visudo -cf %s'
