- name: install Debian packages
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: install SUSE packages
  import_tasks: suse.yml
  when: ansible_os_family == "Suse"

- name: install other packages
  import_tasks: other.yml
  vars:
    families:
      - "Debian"
  when: ansible_os_family in families

- name: ensure ~/.config exists
  ansible.builtin.file:
    path: ~/.config
    state: directory

- name: sync config for LOCAL
  import_tasks: local.yml
  when: inventory_hostname in groups["local"]

- name: sync config for REMOTE
  import_tasks: remote.yml
  when: inventory_hostname in groups["remote"]
